Error in <TNetXNGFile::Open>: [ERROR] Server responded with an error: [3000] Unable to open /store/mc/RunIIAutumn18NanoAODv7/GluGluToRadionToHHTo2B2Tau_M-320_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/100000/50BC1651-1605-2B44-9CAB-B2DB456980F0.root; Invalid argument

Error in <TNetXNGFile::Open>: [ERROR] Server responded with an error: [3000] Unable to open /store/mc/RunIIAutumn18NanoAODv7/GluGluToRadionToHHTo2B2Tau_M-320_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/120000/C969FD5F-8FDC-D34A-B124-69F83F619093.root; Invalid argument

Error in <TNetXNGFile::Open>: [ERROR] Server responded with an error: [3000] Unable to open /store/mc/RunIIAutumn18NanoAODv7/GluGluToRadionToHHTo2B2Tau_M-320_narrow_TuneCP5_PSWeights_13TeV-madgraph-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/260000/A9B4D25D-5526-4247-99E5-8F9A3A8B3257.root; Invalid argument

TClass::Init:0: RuntimeWarning: no dictionary for class edm::Hash<1> is available
TClass::Init:0: RuntimeWarning: no dictionary for class edm::ProcessHistory is available
TClass::Init:0: RuntimeWarning: no dictionary for class edm::ProcessConfiguration is available
TClass::Init:0: RuntimeWarning: no dictionary for class edm::ParameterSetBlob is available
TClass::Init:0: RuntimeWarning: no dictionary for class pair<edm::Hash<1>,edm::ParameterSetBlob> is available
TTreeReader::SetEntryBase():0: RuntimeWarning: There was an issue opening the last file associated to the TChain being processed.
Traceback (most recent call last):
  File "/afs/cern.ch/work/v/vdamante/public/analysis/triggerStudiesAnalysis.py", line 1395, in <module>
    path_perf_withEff = [(filter_str, p[1].GetValue()/N_orig.GetValue(), math.sqrt(p[1].GetValue())/N_orig.GetValue()) for p in path_perf]
  File "/afs/cern.ch/work/v/vdamante/public/analysis/triggerStudiesAnalysis.py", line 1395, in <listcomp>
    path_perf_withEff = [(filter_str, p[1].GetValue()/N_orig.GetValue(), math.sqrt(p[1].GetValue())/N_orig.GetValue()) for p in path_perf]
cppyy.gbl.std.runtime_error: const double& ROOT::RDF::RResultPtr<double>::GetValue() =>
    runtime_error: An error was encountered while processing the data. TTreeReader status code is: 5
