TClass::Init:0: RuntimeWarning: no dictionary for class edm::ProcessHistory is available
TClass::Init:0: RuntimeWarning: no dictionary for class edm::ProcessConfiguration is available
TClass::Init:0: RuntimeWarning: no dictionary for class edm::ParameterSetBlob is available
TClass::Init:0: RuntimeWarning: no dictionary for class edm::Hash<1> is available
TClass::Init:0: RuntimeWarning: no dictionary for class pair<edm::Hash<1>,edm::ParameterSetBlob> is available
Traceback (most recent call last):
  File "/afs/cern.ch/work/v/vdamante/public/analysis/triggerStudiesAnalysis.py", line 1386, in <module>
    current_paths = [ (p, (triggers[p]["eff_lumi"]/total_lumi[str(args.year)])) for p in current_paths]
  File "/afs/cern.ch/work/v/vdamante/public/analysis/triggerStudiesAnalysis.py", line 1386, in <listcomp>
    current_paths = [ (p, (triggers[p]["eff_lumi"]/total_lumi[str(args.year)])) for p in current_paths]
KeyError: ''
